CREATE TABLE client(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(75) NOT NULL,
    lastname VARCHAR(75) NOT NULL,
    docnumber VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE product(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(150),
    code VARCHAR(50) UNIQUE NOT NULL,
    stock INTEGER,
    price DOUBLE
);

CREATE TABLE factura(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    id_client INTEGER FOREIGN KEY AUTO_INCREMENT,
    total INTEGER,
    fecha DATE
);

CREATE TABLE detalle_factura(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    id_factura INTEGER FOREIGN KEY AUTO_INCREMENT,
    id_producto INTEGER FOREIGN KEY AUTO_INCREMENT,
    cantidad INTEGER,
    precio DOUBLE
)